development:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: 5
  username: root
  password: root
  host: <%= 'localhost' %>
  port: <%= '5432' %>

test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_test
  pool: 5
  username: root
  password: root
  host: <%= 'localhost' %>
  port: <%= '5432' %>

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production
  pool: 5
  username: root
  password: root
  host: <%= 'localhost' %>
  port: <%= '5432' %>